# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProduct(object):
    def setupUi(self, AddProduct):
        AddProduct.setObjectName("AddProduct")
        AddProduct.resize(903, 605)
        self.textEdit = QtWidgets.QTextEdit(AddProduct)
        self.textEdit.setGeometry(QtCore.QRect(250, 300, 351, 161))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(AddProduct)
        self.label_4.setGeometry(QtCore.QRect(130, 340, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(AddProduct)
        self.pushButton.setGeometry(QtCore.QRect(260, 520, 171, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AddProduct)
        self.pushButton_2.setGeometry(QtCore.QRect(724, 22, 131, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(AddProduct)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 50, 471, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_2.addWidget(self.doubleSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(AddProduct)
        self.pushButton_2.clicked.connect(AddProduct.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddProduct)

    def retranslateUi(self, AddProduct):
        _translate = QtCore.QCoreApplication.translate
        AddProduct.setWindowTitle(_translate("AddProduct", "Dialog"))
        self.label_4.setText(_translate("AddProduct", "信息"))
        self.pushButton.setText(_translate("AddProduct", "确定"))
        self.pushButton_2.setText(_translate("AddProduct", "返回"))
        self.label.setText(_translate("AddProduct", "名称"))
        self.label_2.setText(_translate("AddProduct", "库存"))
        self.label_3.setText(_translate("AddProduct", "原价"))
