# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminLogin(object):
    def setupUi(self, AdminLogin):
        AdminLogin.setObjectName("AdminLogin")
        AdminLogin.resize(721, 565)
        self.pushButton = QtWidgets.QPushButton(AdminLogin)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AdminLogin)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 410, 131, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(AdminLogin)
        self.label_3.setGeometry(QtCore.QRect(250, 30, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(AdminLogin)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 130, 421, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(AdminLogin)
        self.checkBox.setGeometry(QtCore.QRect(550, 290, 161, 41))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(AdminLogin)
        self.pushButton.clicked.connect(AdminLogin.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AdminLogin)

    def retranslateUi(self, AdminLogin):
        _translate = QtCore.QCoreApplication.translate
        AdminLogin.setWindowTitle(_translate("AdminLogin", "Dialog"))
        self.pushButton.setText(_translate("AdminLogin", "返回上一级"))
        self.pushButton_2.setText(_translate("AdminLogin", "登录"))
        self.label_3.setText(_translate("AdminLogin", "管理员登录"))
        self.label.setText(_translate("AdminLogin", "账号"))
        self.label_2.setText(_translate("AdminLogin", "密码"))
        self.checkBox.setText(_translate("AdminLogin", "可见/隐藏"))
