# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoCart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GoCart(object):
    def setupUi(self, GoCart):
        GoCart.setObjectName("GoCart")
        GoCart.resize(1804, 669)
        self.tableWidget = QtWidgets.QTableWidget(GoCart)
        self.tableWidget.setGeometry(QtCore.QRect(50, 90, 1581, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(GoCart)
        self.pushButton.setGeometry(QtCore.QRect(140, 530, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(GoCart)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 530, 91, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(GoCart)
        self.pushButton_3.setGeometry(QtCore.QRect(1040, 510, 121, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(GoCart)
        self.pushButton_4.setGeometry(QtCore.QRect(1080, 20, 121, 41))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(GoCart)
        self.pushButton_4.clicked.connect(GoCart.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GoCart)

    def retranslateUi(self, GoCart):
        _translate = QtCore.QCoreApplication.translate
        GoCart.setWindowTitle(_translate("GoCart", "Form"))
        self.pushButton.setText(_translate("GoCart", "减少"))
        self.pushButton_2.setText(_translate("GoCart", "增加"))
        self.pushButton_3.setText(_translate("GoCart", "结算"))
        self.pushButton_4.setText(_translate("GoCart", "返回"))
