# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GoShoping.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GoShoping(object):
    def setupUi(self, GoShoping):
        GoShoping.setObjectName("GoShoping")
        GoShoping.resize(1759, 663)
        self.tableWidget = QtWidgets.QTableWidget(GoShoping)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 150, 1421, 381))
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(GoShoping)
        self.pushButton.setGeometry(QtCore.QRect(540, 570, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(GoShoping)
        self.label.setGeometry(QtCore.QRect(50, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(GoShoping)
        self.lineEdit.setGeometry(QtCore.QRect(420, 70, 91, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(GoShoping)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 70, 111, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser = QtWidgets.QTextBrowser(GoShoping)
        self.textBrowser.setGeometry(QtCore.QRect(1490, 150, 241, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(GoShoping)
        self.label_2.setGeometry(QtCore.QRect(1500, 100, 151, 41))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(GoShoping)
        self.comboBox.setGeometry(QtCore.QRect(50, 70, 181, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(GoShoping)
        self.pushButton_2.setGeometry(QtCore.QRect(1550, 30, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(GoShoping)
        self.pushButton_2.clicked.connect(GoShoping.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GoShoping)

    def retranslateUi(self, GoShoping):
        _translate = QtCore.QCoreApplication.translate
        GoShoping.setWindowTitle(_translate("GoShoping", "Form"))
        self.pushButton.setText(_translate("GoShoping", "添加到购物车"))
        self.label.setText(_translate("GoShoping", "商品列表"))
        self.pushButton_4.setText(_translate("GoShoping", "搜索名称"))
        self.label_2.setText(_translate("GoShoping", "商品描述"))
        self.comboBox.setItemText(0, _translate("GoShoping", "价格升序"))
        self.comboBox.setItemText(1, _translate("GoShoping", "价格降序"))
        self.comboBox.setItemText(2, _translate("GoShoping", "ID升序"))
        self.comboBox.setItemText(3, _translate("GoShoping", "ID降序"))
        self.pushButton_2.setText(_translate("GoShoping", "关闭"))
