# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserLogin(object):
    def setupUi(self, UserLogin):
        UserLogin.setObjectName("UserLogin")
        UserLogin.resize(724, 506)
        self.pushButton = QtWidgets.QPushButton(UserLogin)
        self.pushButton.setGeometry(QtCore.QRect(220, 410, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(UserLogin)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 171, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(UserLogin)
        self.checkBox.setGeometry(QtCore.QRect(490, 290, 181, 31))
        self.checkBox.setObjectName("checkBox")
        self.layoutWidget = QtWidgets.QWidget(UserLogin)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 160, 281, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(UserLogin)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(UserLogin)
        self.pushButton_2.clicked.connect(UserLogin.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserLogin)

    def retranslateUi(self, UserLogin):
        _translate = QtCore.QCoreApplication.translate
        UserLogin.setWindowTitle(_translate("UserLogin", "Dialog"))
        self.pushButton.setText(_translate("UserLogin", "确认登录"))
        self.pushButton_2.setText(_translate("UserLogin", "返回上一级"))
        self.checkBox.setText(_translate("UserLogin", "可见/隐藏"))
        self.label.setText(_translate("UserLogin", "账号"))
        self.label_2.setText(_translate("UserLogin", "密码"))
        self.label_3.setText(_translate("UserLogin", "欢迎登录"))
