# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserRegister(object):
    def setupUi(self, UserRegister):
        UserRegister.setObjectName("UserRegister")
        UserRegister.resize(681, 487)
        self.pushButton = QtWidgets.QPushButton(UserRegister)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 141, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(UserRegister)
        self.label.setGeometry(QtCore.QRect(220, 20, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(UserRegister)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 150, 441, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(UserRegister)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 370, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(UserRegister)
        self.pushButton.clicked.connect(UserRegister.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserRegister)

    def retranslateUi(self, UserRegister):
        _translate = QtCore.QCoreApplication.translate
        UserRegister.setWindowTitle(_translate("UserRegister", "Dialog"))
        self.pushButton.setText(_translate("UserRegister", "返回上一级"))
        self.label.setText(_translate("UserRegister", "欢迎新用户注册"))
        self.label_2.setText(_translate("UserRegister", "姓名"))
        self.label_3.setText(_translate("UserRegister", "密码"))
        self.label_4.setText(_translate("UserRegister", "性别"))
        self.label_5.setText(_translate("UserRegister", "电话"))
        self.label_6.setText(_translate("UserRegister", "收货地址"))
        self.comboBox.setItemText(0, _translate("UserRegister", "男"))
        self.comboBox.setItemText(1, _translate("UserRegister", "女"))
        self.pushButton_2.setText(_translate("UserRegister", "注册"))
