# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserShowHistory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserShowHistory(object):
    def setupUi(self, UserShowHistory):
        UserShowHistory.setObjectName("UserShowHistory")
        UserShowHistory.resize(1055, 572)
        self.tableWidget = QtWidgets.QTableWidget(UserShowHistory)
        self.tableWidget.setGeometry(QtCore.QRect(35, 140, 991, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(UserShowHistory)
        self.pushButton.setGeometry(QtCore.QRect(40, 490, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(UserShowHistory)
        self.comboBox.setGeometry(QtCore.QRect(40, 50, 171, 61))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(UserShowHistory)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 50, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(UserShowHistory)
        self.pushButton_3.setGeometry(QtCore.QRect(860, 40, 141, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(UserShowHistory)
        self.pushButton_4.setGeometry(QtCore.QRect(574, 50, 131, 61))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(UserShowHistory)
        self.pushButton_3.clicked.connect(UserShowHistory.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserShowHistory)

    def retranslateUi(self, UserShowHistory):
        _translate = QtCore.QCoreApplication.translate
        UserShowHistory.setWindowTitle(_translate("UserShowHistory", "Form"))
        self.pushButton.setText(_translate("UserShowHistory", "查看详情"))
        self.comboBox.setItemText(0, _translate("UserShowHistory", "按日期升序"))
        self.comboBox.setItemText(1, _translate("UserShowHistory", "按日期降序"))
        self.comboBox.setItemText(2, _translate("UserShowHistory", "按金额升序"))
        self.comboBox.setItemText(3, _translate("UserShowHistory", "按金额降序"))
        self.pushButton_2.setText(_translate("UserShowHistory", "按时间区间搜索"))
        self.pushButton_3.setText(_translate("UserShowHistory", "返回"))
        self.pushButton_4.setText(_translate("UserShowHistory", "重置"))
