# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserShowHistoryItems.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserShowHistoryItems(object):
    def setupUi(self, UserShowHistoryItems):
        UserShowHistoryItems.setObjectName("UserShowHistoryItems")
        UserShowHistoryItems.resize(1436, 582)
        self.tableWidget = QtWidgets.QTableWidget(UserShowHistoryItems)
        self.tableWidget.setGeometry(QtCore.QRect(60, 110, 1211, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(UserShowHistoryItems)
        self.pushButton.setGeometry(QtCore.QRect(1090, 20, 181, 61))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(UserShowHistoryItems)
        self.pushButton.clicked.connect(UserShowHistoryItems.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserShowHistoryItems)

    def retranslateUi(self, UserShowHistoryItems):
        _translate = QtCore.QCoreApplication.translate
        UserShowHistoryItems.setWindowTitle(_translate("UserShowHistoryItems", "Dialog"))
        self.pushButton.setText(_translate("UserShowHistoryItems", "返回"))
