# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserMain(object):
    def setupUi(self, UserMain):
        UserMain.setObjectName("UserMain")
        UserMain.resize(800, 619)
        self.centralwidget = QtWidgets.QWidget(UserMain)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 40, 200, 200))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 260, 200, 200))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 260, 200, 200))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 480, 300, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 40, 200, 200))
        self.pushButton_5.setObjectName("pushButton_5")
        UserMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UserMain)
        self.statusbar.setObjectName("statusbar")
        UserMain.setStatusBar(self.statusbar)

        self.retranslateUi(UserMain)
        self.pushButton_4.clicked.connect(UserMain.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserMain)

    def retranslateUi(self, UserMain):
        _translate = QtCore.QCoreApplication.translate
        UserMain.setWindowTitle(_translate("UserMain", "用户窗口"))
        self.pushButton.setText(_translate("UserMain", "去购物"))
        self.pushButton_2.setText(_translate("UserMain", "修改个人信息"))
        self.pushButton_3.setText(_translate("UserMain", "查询历史记录"))
        self.pushButton_4.setText(_translate("UserMain", "退出"))
        self.pushButton_5.setText(_translate("UserMain", "购物车"))
