# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserModifyInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserModifyInfo(object):
    def setupUi(self, UserModifyInfo):
        UserModifyInfo.setObjectName("UserModifyInfo")
        UserModifyInfo.resize(681, 535)
        self.layoutWidget = QtWidgets.QWidget(UserModifyInfo)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 50, 431, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_6 = QtWidgets.QPushButton(UserModifyInfo)
        self.pushButton_6.setGeometry(QtCore.QRect(564, 20, 81, 31))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(UserModifyInfo)
        self.pushButton_6.clicked.connect(UserModifyInfo.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UserModifyInfo)

    def retranslateUi(self, UserModifyInfo):
        _translate = QtCore.QCoreApplication.translate
        UserModifyInfo.setWindowTitle(_translate("UserModifyInfo", "Form"))
        self.pushButton.setText(_translate("UserModifyInfo", "更改姓名"))
        self.pushButton_2.setText(_translate("UserModifyInfo", "更改密码"))
        self.pushButton_3.setText(_translate("UserModifyInfo", "更改手机号"))
        self.pushButton_4.setText(_translate("UserModifyInfo", "更改地址"))
        self.pushButton_5.setText(_translate("UserModifyInfo", "更改性别"))
        self.comboBox.setItemText(0, _translate("UserModifyInfo", "男"))
        self.comboBox.setItemText(1, _translate("UserModifyInfo", "女"))
        self.pushButton_6.setText(_translate("UserModifyInfo", "返回"))
